### ISSUE TITLE
How to deploy spring boot application through kubernetes and how to specify the neo4j bolt url

### ISSUE THREAD

**Issue by Balatriveni** [neo4j-contrib/neo4j-streams#130]
[deployment.txt](https://github.com/neo4j-contrib/neo4j-streams/files/2746663/deployment.txt)

## Guidelines
will it possible to provide github example application which will be deployed through kubernetes.

I have created a sample application which connects to neo4j and retrieves the data. When we deploy the application through kubernetes we always get neo4j connection issue
But I can connect to the server through local. We have deployed neo4j server in aws. 
also please find kubernetes deployment.yaml
rs AddressSet=[epmdbdev02.nonprod.productmdm.vip.nordstrom.com:7687], writers AddressSet=[], readers AddressSet=[]
2019-01-10 18:41:11.239 ERROR 9 --- [nio-8080-exec-2] LoadBalancer                             : Failed to resolve URI `epmdbdev02.nonprod.productmdm.vip.nordstrom.com:7687` to IPs due to error: epmdbdev02.nonprod.productmdm.vip.nordstrom.com: Name or service not known

java.net.UnknownHostException: epmdbdev02.nonprod.productmdm.vip.nordstrom.com: Name or service not known
        at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method) ~[?:1.8.0_181]
        at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:929) ~[?:1.8.0_181]
        at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1324) ~[?:1.8.0_181]

### Simple Dataset (where it's possibile)

```
//Insert here a set of Cypher statements that helps us to reproduce the problem

```

### Steps (Mandatory)

  1.
  1.
  1.

## Specifications (Mandatory)

Currently used versions

### Versions

  - OS:
  - Neo4j:
  - Neo4j-Streams:

**Comment by conker84** [comment]
Sorry @Balatriveni this is a wrong place to do this kind of question, if you have troubles with the neo4j deployment on Kubernetes please refer on:
https://github.com/neo4j-contrib/kubernetes-neo4j
