### ISSUE TITLE
java.lang.NoClassDefFoundError: org/neo4j/kernel/impl/logging/LogService

### ISSUE THREAD

**Issue by uwegeercken** [neo4j-contrib/neo4j-streams#170]
when I use the neo4j-streams-3.4.1.jar and start the database I get following error:

Caused by: **java.lang.NoClassDefFoundError: org/neo4j/kernel/impl/logging/LogService**
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetPublicMethods(Class.java:2902)
	at java.lang.Class.getMethods(Class.java:1615)
	at sun.misc.ProxyGenerator.generateClassFile(ProxyGenerator.java:451)
	at sun.misc.ProxyGenerator.generateProxyClass(ProxyGenerator.java:339)
	at java.lang.reflect.Proxy$ProxyClassFactory.apply(Proxy.java:639)
	at java.lang.reflect.Proxy$ProxyClassFactory.apply(Proxy.java:557)
	at java.lang.reflect.WeakCache$Factory.get(WeakCache.java:230)
	at java.lang.reflect.WeakCache.get(WeakCache.java:127)
	at java.lang.reflect.Proxy.getProxyClass0(Proxy.java:419)
	at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:719)
	at org.neo4j.kernel.impl.util.DependenciesProxy.dependencies(DependenciesProxy.java:55)
	at org.neo4j.kernel.extension.AbstractKernelExtensions.getKernelExtensionDependencies(AbstractKernelExtensions.java:114)
	at org.neo4j.kernel.extension.AbstractKernelExtensions.init(AbstractKernelExtensions.java:61)
	... 13 more
Caused by: java.lang.ClassNotFoundException: org.neo4j.kernel.impl.logging.LogService
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

If I remove the streams jar file, then the database starts up correctly.

Expected Behavior (Mandatory)
neo4j database should start correctly

Actual Behavior (Mandatory)
database does not start exception thrown

How to Reproduce the Problem
- download neo4j-streams-3.4.1.jar
- create a new database version 3.5.2 in neo4j desktop 1.1.20
- copy neo4j-streams-3.4.1.jar into the plugins folder
- start the database

## Specifications (Mandatory)
neo4j desktop 1.1.20

### Versions
  - OS: Fedora 29
  - Neo4j: 1.1.20
  - Neo4j-Streams: 3.4.1

**Comment by jexp** [comment]
You need to use version 3.5.x of neo4j streams for your neo4j Version

**Comment by uwegeercken** [comment]
ok Michael, do you have a link?

**Comment by uwegeercken** [comment]
got it...

**Comment by uwegeercken** [comment]
cool. it works. I was not aware that there is a 3.5 version. So I will start testing..
