### ISSUE TITLE
Validate configuration before attempting to start

### ISSUE THREAD

**Issue by moxious** [neo4j-contrib/neo4j-streams#181]
When given an empty config, you get this error on startup.

This error is fairly difficult to debug because it doesn't say anything, but its root cause is:

```
kafka.bootstrap.servers=
```

```
May 24 17:29:31 supermax-core-vm-3 pre-neo4j.sh[10722]: 2019-05-24 17:29:31.238+0000 INFO  Initializing Kafka Connector
May 24 17:29:34 supermax-core-vm-3 pre-neo4j.sh[10722]: 2019-05-24 17:29:34.047+0000 INFO  Initialising the Streams Source module
May 24 17:29:34 supermax-core-vm-3 pre-neo4j.sh[10722]: org.apache.kafka.common.KafkaException: Failed to construct kafka producer
May 24 17:29:34 supermax-core-vm-3 pre-neo4j.sh[10722]:         at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:441)
May 24 17:29:34 supermax-core-vm-3 pre-neo4j.sh[10722]:         at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:297)
May 24 17:29:34 supermax-core-vm-3 pre-neo4j.sh[10722]:         at streams.kafka.Neo4jKafkaProducer.<init>(KafkaEventRouter.kt:103)
May 24 17:29:34 supermax-core-vm-3 pre-neo4j.sh[10722]:         at streams.kafka.KafkaEventRouter.start(KafkaEventRouter.kt:36)
May 24 17:29:34 supermax-core-vm-3 pre-neo4j.sh[10722]:         at streams.StreamsEventRouterLifecycle.start(StreamsExtensionFactory.kt:41)
May 24 17:29:34 supermax-core-vm-3 pre-neo4j.sh[10722]:         at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
May 24 17:29:34 supermax-core-vm-3 pre-neo4j.sh[10722]:         at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
May 24 17:29:34 supermax-core-vm-3 pre-neo4j.sh[10722]:         at org.neo4j.kernel.extension.AbstractKernelExtensions.start(AbstractKernelExtensions.java:82)
May 24 17:29:34 supermax-core-vm-3 pre-neo4j.sh[10722]:         at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
May 24 17:29:34 supermax-core-vm-3 pre-neo4j.sh[10722]:         at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
May 24 17:29:34 supermax-core-vm-3 pre-neo4j.sh[10722]:         at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
May 24 17:29:34 supermax-core-vm-3 pre-neo4j.sh[10722]:         at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
May 24 17:29:34 supermax-core-vm-3 pre-neo4j.sh[10722]:         at org.neo4j.kernel.NeoStoreDataSource.start(NeoStoreDataSource.java:434)
May 24 17:29:34 supermax-core-vm-3 pre-neo4j.sh[10722]:         at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
May 24 17:29:34 supermax-core-vm-3 pre-neo4j.sh[10722]:         at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
May 24 17:29:34 supermax-core-vm-3 pre-neo4j.sh[10722]:         at org.neo4j.kernel.impl.transaction.state.DataSourceManager.start(DataSourceManager.java:116)
May 24 17:29:34 supermax-core-vm-3 pre-neo4j.sh[10722]:         at org.neo4j.causalclustering.catchup.storecopy.LocalDatabase.start(LocalDatabase.java:86)
May 24 17:29:34 supermax-core-vm-3 pre-neo4j.sh[10722]:         at org.neo4j.causalclustering.core.state.CoreLife.start0(CoreLife.java:80)
May 24 17:29:34 supermax-core-vm-3 pre-neo4j.sh[10722]:         at org.neo4j.kernel.lifecycle.SafeLifecycle.transition(SafeLifecycle.java:124)
```

**Comment by moxious** [comment]
Related: #193 

Config should still be validated and debug messages printed to let the user know what went wrong though.
