### ISSUE TITLE
Kafka even sink with manual commit fails with multiple topic subscriptions

### ISSUE THREAD

**Issue by sintezcs** [neo4j-contrib/neo4j-streams#186]
I've built the plugin from source to try the latest functionality from https://github.com/neo4j-contrib/neo4j-streams/pull/178.

Neo4J streams plugin fails to process the messages from multiple topics if `kafka.enable.auto.commit` is disabled. **If you leave only one topic in the configuration - everything works fine.**

## Expected Behavior
Neo4J can receive events from both `maxwell_project` and `maxwell_artist` topics and process them with the corresponding CYPHER queries.

## Actual Behavior
Neo4J raises an error when an event comes to any of the topics:
```
2019-06-03 10:34:57.406+0000 ERROR Collection is empty. Collection is empty.
java.util.NoSuchElementException: Collection is empty.
	at kotlin.collections.CollectionsKt___CollectionsKt.last(_Collections.kt:348)
	at streams.kafka.KafkaManualCommitEventConsumer.readSimple(KafkaEventSink.kt:229)
	at streams.kafka.KafkaManualCommitEventConsumer.read(KafkaEventSink.kt:276)
	at streams.StreamsEventConsumer.read$default(StreamsEventSink.kt:29)
	at streams.kafka.KafkaEventSink$createJob$1.invokeSuspend(KafkaEventSink.kt:85)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
	at kotlinx.coroutines.DispatchedTask$DefaultImpls.run(Dispatched.kt:235)
	at kotlinx.coroutines.DispatchedContinuation.run(Dispatched.kt:81)
	at kotlinx.coroutines.scheduling.Task.run(Tasks.kt:94)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:586)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:732)
```

### Steps (Mandatory)

  1. Disable the auto-commit 
`kafka.enable.auto.commit=false`
  2. Subscribe to mutliple (more than 1) topics:
```
kafka.enable.auto.commit=false
streams.sink.enabled=true

streams.sink.topic.cypher.maxwell_artist=\
WITH event.data AS data \
    MERGE (ar:Artist {id: toInteger(data.artist_id)}) \
      ON CREATE SET ar.name = data.artist_name \
      ON MATCH SET ar.name = data.artist_name

streams.sink.topic.cypher.maxwell_project=\
WITH event.data AS data \
    MATCH (ar:Artist {id: toInteger(data.artist_id)}) \
    MERGE (pr:Project {id: toInteger(data.project_id)}) \
      ON CREATE SET pr.name = data.project_name \
      ON MATCH SET pr.name = data.project_name \
    MERGE (ar)-[:HAS_PROJECT]->(pr)
```

## Specifications

Currently used versions

### Versions

  - OS: MacOS  10.14.5
  - Neo4j: 3.4.1
  - Neo4j-Streams: 3.4.1 (built from sources)

**Comment by conker84** [comment]
@sintezcs thanks a lot for the feedback, I'm on it. I'll be back soon!

**Comment by conker84** [comment]
[neo4j-streams-3.4.1.jar.zip](https://github.com/neo4j-contrib/neo4j-streams/files/3251917/neo4j-streams-3.4.1.jar.zip)
Hi @sintezcs can you try with the jar above?
Thanks a lot

**Comment by sintezcs** [comment]
@conker84 thank you for getting back to me! Sure, I'll try this build right now.

**Comment by sintezcs** [comment]
Cool, I see that this error does not happen anymore. I see another kind of issue. Looks like smth is wrong with the offset management. Because I see that one message is being picked up from the stream again after restarting Neo4J. Also I am a bit concerned about this:
```
2019-06-04 11:25:35.153+0000 DEBUG for maxwell__artist partition 0, the retrieved offset is: null
2019-06-04 11:25:35.154+0000 DEBUG for maxwell__project partition 0, the retrieved offset is: null
2019-06-04 11:25:35.154+0000 DEBUG for maxwell__product partition 0, the retrieved offset is: null
```

Full log:

```
Starting Neo4j.
2019-06-04 11:25:24.286+0000 INFO  ======== Neo4j 3.4.10 ========
2019-06-04 11:25:24.322+0000 INFO  Starting...
2019-06-04 11:25:25.324+0000 INFO  Initializing Kafka Connector
2019-06-04 11:25:26.358+0000 INFO  Initiating metrics...
2019-06-04 11:25:27.776+0000 INFO  Initialising the Streams Source module
2019-06-04 11:25:28.324+0000 INFO  Kafka Connector started
2019-06-04 11:25:28.324+0000 INFO  Streams Source module initialised
2019-06-04 11:25:28.326+0000 INFO  Sending metrics to CSV file at /Users/alexeyminakov/Library/Application Support/Neo4j Desktop/Application/neo4jDatabases/database-7068f5fe-dbee-485b-94b2-4f6ae400a034/installation-3.4.10/metrics
2019-06-04 11:25:28.578+0000 INFO  Bolt enabled on 127.0.0.1:7687.
2019-06-04 11:25:29.904+0000 INFO  Initialising the Streams Sink module
2019-06-04 11:25:31.157+0000 INFO  Starting the Kafka Sink
2019-06-04 11:25:31.248+0000 INFO  Creating Sink daemon Job
2019-06-04 11:25:31.250+0000 INFO  Kafka Sink started
2019-06-04 11:25:31.251+0000 DEBUG Subscribed topics with Cypher queries: {maxwell__project=WITH event.data AS data MATCH (ar:Artist {id: toInteger(data.artist_id)}) MERGE (pr:Project {id: toInteger(data.project_id)}) ON CREATE SET pr.name = data.project_name ON MATCH SET pr.name = data.project_name MERGE (ar)-[:HAS_PROJECT]->(pr), maxwell__product=WITH event.data AS data MATCH (pr:Project {id: toInteger(data.project_id)}) MERGE (p:Product {id: toInteger(data.release_id)}) ON CREATE SET p.name = data.release_name ON MATCH SET p.name = data.release_name MERGE (pr)-[:HAS_PRODUCT]->(p), maxwell__artist=WITH event.data AS data MERGE (ar:Artist {id: toInteger(data.artist_id)}) ON CREATE SET ar.name = data.artist_name ON MATCH SET ar.name = data.artist_name}
2019-06-04 11:25:31.251+0000 DEBUG Subscribed topics with CDC configuration: {CDC_SOURCE_ID=[], CDC_SCHEMA=[]}
2019-06-04 11:25:31.251+0000 INFO  Streams Sink module initialised
2019-06-04 11:25:31.359+0000 WARN  Server thread metrics not available (missing neo4j.server.threads.jetty.all)
2019-06-04 11:25:31.360+0000 WARN  Server thread metrics not available (missing neo4j.server.threads.jetty.idle)
2019-06-04 11:25:32.191+0000 INFO  Started.
2019-06-04 11:25:32.434+0000 DEBUG Adding JAXRS classes [org.neo4j.server.rest.MasterInfoService, org.neo4j.server.rest.CoreDatabaseAvailabilityService, org.neo4j.server.rest.ReadReplicaDatabaseAvailabilityService, org.neo4j.server.rest.causalclustering.CausalClusteringService] at [/db/manage]
2019-06-04 11:25:32.434+0000 INFO  Mounted REST API at: /db/manage
2019-06-04 11:25:32.436+0000 DEBUG Adding JAXRS classes [org.neo4j.server.rest.discovery.DiscoveryService, org.neo4j.server.rest.dbms.UserService] at [/]
2019-06-04 11:25:32.444+0000 DEBUG Adding JAXRS classes [org.neo4j.server.rest.web.RestfulGraphDatabase, org.neo4j.server.rest.web.TransactionalService, org.neo4j.server.rest.web.CypherService, org.neo4j.server.rest.web.DatabaseMetadataService, org.neo4j.server.rest.web.ExtensionService, org.neo4j.server.rest.web.ResourcesService, org.neo4j.server.rest.web.BatchOperationService] at [/db/data]
2019-06-04 11:25:32.447+0000 DEBUG Adding JAXRS classes [org.neo4j.server.rest.management.JmxService, org.neo4j.server.rest.management.RootService, org.neo4j.server.rest.management.VersionAndEditionService] at [/db/manage]
2019-06-04 11:25:32.447+0000 DEBUG Adding JAXRS classes [org.neo4j.server.rest.management.console.ConsoleService] at [/db/manage]
2019-06-04 11:25:32.512+0000 INFO  Server thread metrics has been registered successfully
2019-06-04 11:25:32.527+0000 DEBUG Mounting servlet at [/db/manage]
2019-06-04 11:25:32.551+0000 DEBUG Mounting servlet at [/db/data]
2019-06-04 11:25:32.567+0000 DEBUG Mounting servlet at [/]
2019-06-04 11:25:33.175+0000 INFO  Remote interface available at http://localhost:7474/
2019-06-04 11:25:35.153+0000 DEBUG for maxwell__artist partition 0, the retrieved offset is: null
2019-06-04 11:25:35.154+0000 DEBUG for maxwell__project partition 0, the retrieved offset is: null
2019-06-04 11:25:35.154+0000 DEBUG for maxwell__product partition 0, the retrieved offset is: null
2019-06-04 11:25:35.644+0000 DEBUG Reading data from topic maxwell__artist
2019-06-04 11:25:35.909+0000 DEBUG Query statistics:
Properties set: 3

2019-06-04 11:25:53.199+0000 INFO  Neo4j Server shutdown initiated by request
2019-06-04 11:25:53.212+0000 INFO  Stopping...
2019-06-04 11:25:53.243+0000 INFO  Stopping Sink daemon Job
Active database: graph.db
Directories in use:
  home:         /Users/alexeyminakov/Library/Application Support/Neo4j Desktop/Application/neo4jDatabases/database-7068f5fe-dbee-485b-94b2-4f6ae400a034/installation-3.4.10
  config:       /Users/alexeyminakov/Library/Application Support/Neo4j Desktop/Application/neo4jDatabases/database-7068f5fe-dbee-485b-94b2-4f6ae400a034/installation-3.4.10/conf
  logs:         /Users/alexeyminakov/Library/Application Support/Neo4j Desktop/Application/neo4jDatabases/database-7068f5fe-dbee-485b-94b2-4f6ae400a034/installation-3.4.10/logs
  plugins:      /Users/alexeyminakov/Library/Application Support/Neo4j Desktop/Application/neo4jDatabases/database-7068f5fe-dbee-485b-94b2-4f6ae400a034/installation-3.4.10/plugins
  import:       /Users/alexeyminakov/Library/Application Support/Neo4j Desktop/Application/neo4jDatabases/database-7068f5fe-dbee-485b-94b2-4f6ae400a034/installation-3.4.10/import
  data:         /Users/alexeyminakov/Library/Application Support/Neo4j Desktop/Application/neo4jDatabases/database-7068f5fe-dbee-485b-94b2-4f6ae400a034/installation-3.4.10/data
  certificates: /Users/alexeyminakov/Library/Application Support/Neo4j Desktop/Application/neo4jDatabases/database-7068f5fe-dbee-485b-94b2-4f6ae400a034/installation-3.4.10/certificates
  run:          /Users/alexeyminakov/Library/Application Support/Neo4j Desktop/Application/neo4jDatabases/database-7068f5fe-dbee-485b-94b2-4f6ae400a034/installation-3.4.10/run
Starting Neo4j.
2019-06-04 11:25:54.399+0000 INFO  ======== Neo4j 3.4.10 ========
2019-06-04 11:25:54.427+0000 INFO  Starting...
2019-06-04 11:25:55.040+0000 INFO  Initializing Kafka Connector
2019-06-04 11:25:55.866+0000 INFO  Initiating metrics...
2019-06-04 11:25:57.088+0000 INFO  Initialising the Streams Source module
2019-06-04 11:25:57.163+0000 INFO  Kafka Connector started
2019-06-04 11:25:57.163+0000 INFO  Streams Source module initialised
2019-06-04 11:25:57.165+0000 INFO  Sending metrics to CSV file at /Users/alexeyminakov/Library/Application Support/Neo4j Desktop/Application/neo4jDatabases/database-7068f5fe-dbee-485b-94b2-4f6ae400a034/installation-3.4.10/metrics
2019-06-04 11:25:57.370+0000 INFO  Bolt enabled on 127.0.0.1:7687.
2019-06-04 11:25:58.564+0000 INFO  Initialising the Streams Sink module
2019-06-04 11:25:59.592+0000 INFO  Starting the Kafka Sink
2019-06-04 11:25:59.683+0000 INFO  Creating Sink daemon Job
2019-06-04 11:25:59.685+0000 INFO  Kafka Sink started
2019-06-04 11:25:59.686+0000 DEBUG Subscribed topics with Cypher queries: {maxwell__project=WITH event.data AS data MATCH (ar:Artist {id: toInteger(data.artist_id)}) MERGE (pr:Project {id: toInteger(data.project_id)}) ON CREATE SET pr.name = data.project_name ON MATCH SET pr.name = data.project_name MERGE (ar)-[:HAS_PROJECT]->(pr), maxwell__product=WITH event.data AS data MATCH (pr:Project {id: toInteger(data.project_id)}) MERGE (p:Product {id: toInteger(data.release_id)}) ON CREATE SET p.name = data.release_name ON MATCH SET p.name = data.release_name MERGE (pr)-[:HAS_PRODUCT]->(p), maxwell__artist=WITH event.data AS data MERGE (ar:Artist {id: toInteger(data.artist_id)}) ON CREATE SET ar.name = data.artist_name ON MATCH SET ar.name = data.artist_name}
2019-06-04 11:25:59.686+0000 DEBUG Subscribed topics with CDC configuration: {CDC_SOURCE_ID=[], CDC_SCHEMA=[]}
2019-06-04 11:25:59.686+0000 INFO  Streams Sink module initialised
2019-06-04 11:26:00.180+0000 WARN  Server thread metrics not available (missing neo4j.server.threads.jetty.all)
2019-06-04 11:26:00.181+0000 WARN  Server thread metrics not available (missing neo4j.server.threads.jetty.idle)
2019-06-04 11:26:00.294+0000 INFO  Started.
2019-06-04 11:26:00.480+0000 DEBUG Adding JAXRS classes [org.neo4j.server.rest.MasterInfoService, org.neo4j.server.rest.CoreDatabaseAvailabilityService, org.neo4j.server.rest.ReadReplicaDatabaseAvailabilityService, org.neo4j.server.rest.causalclustering.CausalClusteringService] at [/db/manage]
2019-06-04 11:26:00.480+0000 INFO  Mounted REST API at: /db/manage
2019-06-04 11:26:00.481+0000 DEBUG Adding JAXRS classes [org.neo4j.server.rest.discovery.DiscoveryService, org.neo4j.server.rest.dbms.UserService] at [/]
2019-06-04 11:26:00.486+0000 DEBUG Adding JAXRS classes [org.neo4j.server.rest.web.RestfulGraphDatabase, org.neo4j.server.rest.web.TransactionalService, org.neo4j.server.rest.web.CypherService, org.neo4j.server.rest.web.DatabaseMetadataService, org.neo4j.server.rest.web.ExtensionService, org.neo4j.server.rest.web.ResourcesService, org.neo4j.server.rest.web.BatchOperationService] at [/db/data]
2019-06-04 11:26:00.489+0000 DEBUG Adding JAXRS classes [org.neo4j.server.rest.management.JmxService, org.neo4j.server.rest.management.RootService, org.neo4j.server.rest.management.VersionAndEditionService] at [/db/manage]
2019-06-04 11:26:00.490+0000 DEBUG Adding JAXRS classes [org.neo4j.server.rest.management.console.ConsoleService] at [/db/manage]
2019-06-04 11:26:00.536+0000 INFO  Server thread metrics has been registered successfully
2019-06-04 11:26:00.550+0000 DEBUG Mounting servlet at [/db/manage]
2019-06-04 11:26:00.574+0000 DEBUG Mounting servlet at [/db/data]
2019-06-04 11:26:00.588+0000 DEBUG Mounting servlet at [/]
2019-06-04 11:26:01.131+0000 INFO  Remote interface available at http://localhost:7474/
2019-06-04 11:26:03.702+0000 DEBUG for maxwell__artist partition 0, the retrieved offset is: null
2019-06-04 11:26:03.702+0000 DEBUG for maxwell__project partition 0, the retrieved offset is: null
2019-06-04 11:26:03.702+0000 DEBUG for maxwell__product partition 0, the retrieved offset is: null
2019-06-04 11:26:04.183+0000 DEBUG Reading data from topic maxwell__artist
2019-06-04 11:26:04.537+0000 DEBUG Query statistics:
Properties set: 3
```

**Comment by conker84** [comment]
Thanks a lot, the following jar should fix that issue too:
[neo4j-streams-3.4.1.jar.zip](https://github.com/neo4j-contrib/neo4j-streams/files/3253406/neo4j-streams-3.4.1.jar.zip)
Looking forward to your feedback!

**Comment by sintezcs** [comment]
@conker84 I've tried this version and looks like it works! I see the correct offsets after restarting, and I don't see any kotlin errors. Thank you a lot!

When can we expect these fixes to be published and Github and released in a new plugin version?

**Comment by conker84** [comment]
Yes!
