### ISSUE TITLE
Neo4j command execution failed in Zeppelin

### ISSUE THREAD

**Issue by M9T** [neo4j-contrib/neo4j-streams#236]
I executed the `%neo4j
MATCH (n) detach delete n` command. 
![image](https://user-images.githubusercontent.com/46939197/64020176-36848000-cb31-11e9-8077-89c3595d9787.png)

java.net.UnknownHostException
	at sun.nio.ch.Net.translateException(Net.java:155)
	at sun.nio.ch.SocketAdaptor.connect(SocketAdaptor.java:127)
	at org.neo4j.driver.internal.net.ChannelFactory.connect(ChannelFactory.java:79)
	at org.neo4j.driver.internal.net.ChannelFactory.create(ChannelFactory.java:41)
	at org.neo4j.driver.internal.net.SocketClient.start(SocketClient.java:126)
	at org.neo4j.driver.internal.net.SocketConnection.startSocketClient(SocketConnection.java:92)
	at org.neo4j.driver.internal.net.SocketConnection.<init>(SocketConnection.java:67)
	at org.neo4j.driver.internal.net.SocketConnector.createConnection(SocketConnector.java:77)
	at org.neo4j.driver.internal.net.SocketConnector.connect(SocketConnector.java:50)
	at org.neo4j.driver.internal.net.pooling.SocketConnectionPool$ConnectionSupplier.get(SocketConnectionPool.java:204)
	at org.neo4j.driver.internal.net.pooling.SocketConnectionPool$ConnectionSupplier.get(SocketConnectionPool.java:186)
	at org.neo4j.driver.internal.net.pooling.BlockingPooledConnectionQueue.acquire(BlockingPooledConnectionQueue.java:96)
	at org.neo4j.driver.internal.net.pooling.SocketConnectionPool.acquireConnection(SocketConnectionPool.java:137)
	at org.neo4j.driver.internal.net.pooling.SocketConnectionPool.acquire(SocketConnectionPool.java:76)
	at org.neo4j.driver.internal.DirectConnectionProvider.acquireConnection(DirectConnectionProvider.java:47)
	at org.neo4j.driver.internal.DirectConnectionProvider.verifyConnectivity(DirectConnectionProvider.java:67)
	at org.neo4j.driver.internal.DirectConnectionProvider.<init>(DirectConnectionProvider.java:41)
	at org.neo4j.driver.internal.DriverFactory.createDirectDriver(DriverFactory.java:109)
	at org.neo4j.driver.internal.DriverFactory.createDriver(DriverFactory.java:93)
	at org.neo4j.driver.internal.DriverFactory.newInstance(DriverFactory.java:67)
	at org.neo4j.driver.v1.GraphDatabase.driver(GraphDatabase.java:135)
	at org.neo4j.driver.v1.GraphDatabase.driver(GraphDatabase.java:117)
	at org.apache.zeppelin.graph.neo4j.Neo4jConnectionManager.getDriver(Neo4jConnectionManager.java:98)
	at org.apache.zeppelin.graph.neo4j.Neo4jConnectionManager.open(Neo4jConnectionManager.java:104)
	at org.apache.zeppelin.graph.neo4j.Neo4jCypherInterpreter.open(Neo4jCypherInterpreter.java:76)
	at org.apache.zeppelin.interpreter.LazyOpenInterpreter.open(LazyOpenInterpreter.java:69)
	at org.apache.zeppelin.interpreter.remote.RemoteInterpreterServer$InterpretJob.jobRun(RemoteInterpreterServer.java:616)
	at org.apache.zeppelin.scheduler.Job.run(Job.java:188)
	at org.apache.zeppelin.scheduler.ParallelScheduler$JobRunner.run(ParallelScheduler.java:162)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by jexp** [comment]
Did you put in the correct connection url and credentials for your neo4j instance?

**Comment by conker84** [comment]
@M9T are you using the compose file from [here](https://github.com/conker84/leveraging-neo4j-streams)?
In case so please share the output `docker-compose logs -f neo4j`

**Comment by M9T** [comment]
@conker84 Yes I cloned your repo. What I did next: Follow the medium [article](https://medium.com/free-code-camp/how-to-leverage-neo4j-streams-and-build-a-just-in-time-data-warehouse-64adf290f093).
![image](https://user-images.githubusercontent.com/46939197/64041111-e8867100-cb5e-11e9-9e1e-c881f16005cc.png)

**Comment by conker84** [comment]
Can you de-comment the line 34 in the compose file?:
`# NEO4J_dbms_logs_debug_level: DEBUG`
and pass the output of the log?
Thanks

**Comment by M9T** [comment]
For me the output looks the same. @conker84 Any further suggestions?
![image](https://user-images.githubusercontent.com/46939197/64047373-e4fae600-cb6e-11e9-9471-e97b9695ea3b.png)

**Comment by conker84** [comment]
Can you add this volume to the neo4j service:
```
      - ./neo4j/logs:/logs
```

and share the `debug.log` file?
Thanks

**Comment by conker84** [comment]
@M9T ping

**Comment by jexp** [comment]
@M9T ping again!

**Comment by M9T** [comment]
I need to find some time to give it a try. Thanks for the reminder.

**Comment by conker84** [comment]
I'm closing this, please feel free to reopen it in case you have new details
