### ISSUE TITLE
class com.fasterxml.jackson.databind.deser.SettableBeanProperty$Delegating overrides final method getDeclaringClass.()Ljava/lang/Class;

### ISSUE THREAD

**Issue by Tin-Nguyen** [neo4j-contrib/neo4j-streams#254]
# Guidelines

I cannot use neo4j-streams (3.4.4) on my Neo4j 3.4.7 (either community or enterprise) has already had our owned neo4j plugin in `plugins` folder. I'm getting the error below:
```
2019-10-17 02:53:37.312+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@45198fd9' was successfully initialized, but failed to start. Please see the attached cause exception "class com.fasterxml.jackson.databind.deser.SettableBeanProperty$Delegating overrides final method getDeclaringClass.()Ljava/lang/Class;". Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@45198fd9' was successfully initialized, but failed to start. Please see the attached cause exception "class com.fasterxml.jackson.databind.deser.SettableBeanProperty$Delegating overrides final method getDeclaringClass.()Ljava/lang/Class;".
org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@45198fd9' was successfully initialized, but failed to start. Please see the attached cause exception "class com.fasterxml.jackson.databind.deser.SettableBeanProperty$Delegating overrides final method getDeclaringClass.()Ljava/lang/Class;".
        at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:68)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:220)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:111)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:79)
        at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:32)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabase@45198fd9' was successfully initialized, but failed to start. Please see the attached cause exception "class com.fasterxml.jackson.databind.deser.SettableBeanProperty$Delegating overrides final method getDeclaringClass.()Ljava/lang/Class;".
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:466)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:212)
        ... 3 more
Caused by: java.lang.RuntimeException: Error starting org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory, /var/lib/neo4j/data/databases/graph.db
        at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:212)
        at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:125)
        at org.neo4j.server.CommunityNeoServer.lambda$static$0(CommunityNeoServer.java:58)
        at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:88)
```
It seems like there is a conflict on Jackson dependency, but the interesting thing here is my owned plugin doesn't have that dependency in pom.xml file. 

## Expected Behavior (Mandatory)
Run successfully

## Actual Behavior (Mandatory)
Got error like described above

## How to Reproduce the Problem
I can provide the jar file of my owned plugin if necessary.

### Simple Dataset (where it's possibile)
N/A

### Steps (Mandatory)
N/A

## Screenshots (where it's possibile)
N/A

## Specifications (Mandatory)
N/A

Currently used versions

### Versions

  - OS: Docker (MAC OS) latest version
  - Neo4j: 3.4.7
  - Neo4j-Streams: 3.4.4

**Comment by Tin-Nguyen** [comment]
Hi all,

I fixed the issue. I did the same fix as https://github.com/graphaware/neo4j-framework/pull/88 that uses maven-shade-plugin in order to relocation the conflicted package in my owned plugin to another namespace. That should work.
