### ISSUE TITLE
[3.5.5] Error initializing the streaming producer: Failed to create new KafkaAdminClient

### ISSUE THREAD

**Issue by Tin-Nguyen** [neo4j-contrib/neo4j-streams#277]
## Guidelines

I'm trying to upgrade the Neo4j Streams plugin from 3.5.4 to 3.5.5 that has just been released 4 days ago for my Neo4j 3.5.6-enterprise. However I got the below error when starting Neo4j

```
org.apache.kafka.common.KafkaException: Failed to create new KafkaAdminClient
        at org.apache.kafka.clients.admin.KafkaAdminClient.createInternal(KafkaAdminClient.java:407)
        at org.apache.kafka.clients.admin.AdminClient.create(AdminClient.java:55)
        at streams.kafka.KafkaAdminService.<init>(KafkaAdminService.kt:18)
        at streams.kafka.KafkaEventRouter.start(KafkaEventRouter.kt:46)
        at streams.StreamsEventRouterLifecycle.start(StreamsExtensionFactory.kt:48)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
        at org.neo4j.kernel.extension.AbstractKernelExtensions.start(AbstractKernelExtensions.java:82)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
        at org.neo4j.kernel.NeoStoreDataSource.start(NeoStoreDataSource.java:444)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
        at org.neo4j.kernel.impl.transaction.state.DataSourceManager.start(DataSourceManager.java:116)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
        at org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:225)
        at com.neo4j.commercial.edition.CommercialGraphDatabase.<init>(CommercialGraphDatabase.java:20)
        at com.neo4j.server.database.CommercialGraphFactory.newGraphDatabase(CommercialGraphFactory.java:40)
        at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:90)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:180)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:124)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:91)
        at com.neo4j.server.enterprise.CommercialEntryPoint.main(CommercialEntryPoint.java:22)
Caused by: org.apache.kafka.common.config.ConfigException: No resolvable bootstrap urls given in bootstrap.servers
        at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:88)
        at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:47)
        at org.apache.kafka.clients.admin.KafkaAdminClient.createInternal(KafkaAdminClient.java:367)
        ... 27 more
```

Currently used versions

### Versions

  - OS: Docker on MAC
  - Neo4j: 3.5.6 -enterprise
  - Neo4j-Streams: 3.5.5

**Comment by conker84** [comment]
hi @Tin-Nguyen  can you share your compose file?

**Comment by Tin-Nguyen** [comment]
hi @conker84 , please check the docker compose file [here](https://gist.github.com/Tin-Nguyen/08ac7da3af89383d938f4be027dcb7ef)

**Comment by conker84** [comment]
You're missing two env params into the `neo4j` service:
```
      NEO4J_kafka_zookeeper_connect: zookeeper:2181
      NEO4J_kafka_bootstrap_servers: broker:29092
```

**Comment by Tin-Nguyen** [comment]
@conker84 , I did add it into neo4j.conf already. Is it deprecated on the latest version of the plugin (3.5.5)?
Below is my current configuration in neo4j.conf
```
# Neo4j-Streams Kafka Connection
kafka.zookeeper.connect=zookeeper:2181
kafka.bootstrap.servers=kafka:29092
kafka.schema.registry.url=http://schema-registry:8081```

**Comment by Tin-Nguyen** [comment]
it works on my local now after applied the ENV vars you mentioned above @conker84 . It seems the plugin deprecated the configurations in neo4j.conf.

**Comment by conker84** [comment]
We didn't deprecate those configs, I'm guessing where you're using the `neo4j.conf` file because I can't see any reference into the compose file and the Dockerfile. I think that there is a problem in your container configuration. Properties like `NEO4J_kafka_zookeeper_connect` are transformed into `kafka.zookeeper.connect` into the `neo4j.conf` file by the Neo4j Container.
