### ISSUE TITLE
Kafka-connect-sink for neo4j

### ISSUE THREAD

**Issue by kebana23** [neo4j-contrib/neo4j-streams#288]
## How to Reproduce the Problem

We're facing problems trying to use kafka-connect-sink for neo4j,
We get this following error :

`[2020-03-05 13:36:20,088] INFO Loading plugin from: /opt/confluent-5.3.0/plugins/neo4j-kafka-connect-neo4j-1.0.6/lib/kafka-conLoader:222)
[2020-03-05 13:36:20,098] ERROR Stopping due to error (org.apache.kafka.connect.cli.ConnectStandalone:130)
java.lang.NoClassDefFoundError: kotlin/TypeCastException
        at streams.kafka.connect.sink.Neo4jSinkConnector.version(Neo4jSinkConnector.kt:31)
        at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.versionFor(DelegatingClassLoader.java:350)
        at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.versionFor(DelegatingClassLoader.java:355)
        at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.getPluginDesc(DelegatingClassLoader.java:331)
        at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.scanPluginPath(DelegatingClassLoader.java:311)
        at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.scanUrlsAndAddPlugins(DelegatingClassLoader.java:2
        at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.registerPlugin(DelegatingClassLoader.java:236)
        at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.initPluginLoader(DelegatingClassLoader.java:205)
        at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.initLoaders(DelegatingClassLoader.java:182)
        at org.apache.kafka.connect.runtime.isolation.Plugins.<init>(Plugins.java:61)
        at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:79)
Caused by: java.lang.ClassNotFoundException: kotlin.TypeCastException
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at org.apache.kafka.connect.runtime.isolation.PluginClassLoader.loadClass(PluginClassLoader.java:104)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 11 more
`
The way we try to run the kafka-connect-sink plugging is by running a standalone instance of kafka
with this configuration :
**standalone-connect.properties** : 
`bootstrap.servers=hostname.domain:9094

key.converter=org.apache.kafka.connect.json.JsonConverter
value.converter=org.apache.kafka.connect.json.JsonConverter
key.converter.schemas.enable=true
value.converter.schemas.enable=true

offset.storage.file.filename=/tmp/connect_test_neo4j.offset
offset.flush.interval.ms=10000

sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required \
   username="kafka-user" \
   password="kafka-pass";
sasl.mechanism=SCRAM-SHA-256
security.protocol=SASL_SSL

plugin.path=/opt/confluent-5.3.0/share/java,/opt/confluent-5.3.0/plugins/neo4j-kafka-connect-neo4j-1.0.5/lib
`
**kafka-connect-neo4j-sink.properties :**

`name=Neo4jSinkConnector
topics=KafkaTest
connector.class=streams.kafka.connect.sink.Neo4jSinkConnector
errors.retry.timeout=-1
errors.retry.delay.max.ms=1000
errors.tolerance=all
errors.log.enable=true
errors.log.include.messages=true
neo4j.server.uri=bolt://neo4jHostname.domain:7687
neo4j.authentication.basic.username=neo4j
neo4j.authentication.basic.password=neo4j
neo4j.encryption.enabled=false
neo4j.topic.cypher.my-topic=CREATE (n:Test)
value.converter=org.apache.kafka.connect.json.JsonConverter`

### Versions

  - OS: CentOS Linux release 7.6.1810 
  - confluent: 5.3.0
  - kafka-connect-neo4j : 1.0.5 
  - Neo4j: 3.5.14

**Comment by mroiter-larus** [comment]
Hi @kebana23,

could you please provide the commands you run to startup the Confluent platform and a sample of the JSON event you are trying to send?

Thanks in advance

**Comment by kebana23** [comment]
Hi @mroiter-larus ,

Thanks for you response.

In our case, we have already confluent platform installed in a secure virtual machine, that cause access to internet from outside. so we installed the plugging manually we download the jar files and we put them in **/opt/confluent-5.3.0/plugins/neo4j-kafka-connect-neo4j-1.0.5/lib** as recommended in the confluent documentation page:

For the moment, we are just trying to create a simple node  as described in configuration file **kafka-connect-neo4j-sink.properties** :

```
name=Neo4jSinkConnector topics=KafkaTest connector.class=streams.kafka.connect.sink.Neo4jSinkConnector errors.retry.timeout=-1 errors.retry.delay.max.ms=1000 errors.tolerance=all errors.log.enable=true errors.log.include.messages=true neo4j.server.uri=bolt://neo4jHostname.domain:7687 neo4j.authentication.basic.username=neo4j neo4j.authentication.basic.password=neo4j neo4j.encryption.enabled=false
 **neo4j.topic.cypher.my-topic=CREATE (n:Test)** value.converter=org.apache.kafka.connect.json.JsonConverter
```

We run kafka service with this following command : 
service kafka start 
And we run the standalone instance with this command :

`connect-standalone /opt/confluent-5.3.0/etc/kafka-connect-neo4j/connect-standalone.properties /opt/confluent-5.3.0/etc/kafka-connect-neo4j/kafka-connect-neo4j-sink.properties`

**Comment by mroiter-larus** [comment]
Hi @kebana23,

I noticed an inconsistency in the **kafka-connect-neo4j-sink.properties**. More precisely: the value of the property "**topics**" is _KafkaTest_ while the value of the <_topic-name_> in the property `neo4j.topic.cypher.<topic-name>` is "_my-topic_". These two values must be equal, unless more than one topic is declared in the _topics_ property. In this case you have to declare one `neo4j.topic.cypher.<topic-name>` for each topic.

That said, i think there could be a mistake also in the plugin installation. I would suggest you install the plugin following the below steps:
- download the neo4j-kafka-connect-neo4j-1.0.5.zip from [here](https://github.com/neo4j-contrib/neo4j-streams/releases/tag/3.5.5)
- unzip the downloaded file
- move the unzipped folder (neo4j-kafka-connect-neo4j-1.0.5) into the following folder: `<confluent_home_dir>/share/confluent-hub-components`
- go to `<confluent_home_dir>/etc/kafka`. Open the `connect-standalone.properties` file and edit the **plugin.path** property adding the _confluent-hub-components_ dir absolute path: 
`plugin.path=/usr/share/java,<confluent_home_dir>/share/confluent-hub-components`  
- go to `<confluent_home_dir>/share/confluent-hub-components/neo4j-kafka-connect-neo4j-1.0.5/etc`, open and edit `sink-quickstart.properties` file with your desired properties:
>name=Neo4jSinkConnector 
>topics=**KafkaTest** 
>connector.class=streams.kafka.connect.sink.Neo4jSinkConnector 
>errors.retry.timeout=-1 
>errors.retry.delay.max.ms=1000 
>errors.tolerance=all 
>errors.log.enable=true 
>errors.log.include.messages=true 
>neo4j.server.uri=bolt://<**YOUR_NEO4J_HOST**>:7687 
>neo4j.authentication.basic.username=neo4j 
>neo4j.authentication.basic.password=<**YOUR_NEO4J_PASSWORD**> 
>neo4j.encryption.enabled=false
>neo4j.topic.cypher.**KafkaTest**=CREATE (n:Test) 
>value.converter=org.apache.kafka.connect.json.JsonConverter
- start Zookeeper, Kafka and Neo4j
- Be sure to be in the Confluent bin folder (`<confluent_home_dir>/bin`) and start the Kafka connect worker with the following command:
>./connect-standalone ../etc/kafka/connect-standalone.properties ../share/confluent-hub-components/neo4j-kafka-connect-neo4j-1.0.5/etc/sink-quickstart.properties
- Start a kafka-console-producer: 
`./kafka-console-producer --broker-list <YOUR_BROKER_HOST>:9092 --topic KafkaTest`
- Send a JSON event as follow: `{"test": "test"}`
- You should see a new node with label "Test" inside Neo4j

Hope this helps!

**Comment by mroiter-larus** [comment]
Hi @kebana23,

any news about this issue?

Thanks

**Comment by mroiter-larus** [comment]
Hi @kebana23,

any news about this issue?

Thanks

**Comment by moxious** [comment]
Closing for age and non-response.
