### ISSUE TITLE
[ERROR] Tasks 1 cancelled after timeout of 30000 ms

### ISSUE THREAD

**Issue by Tin-Nguyen** [neo4j-contrib/neo4j-streams#428]
## Guidelines

Recently I'm facing with a lots of ERROR logs on my Kafka Connect using Neo4j Sink connector
```
Tasks 1 cancelled after timeout of 30000 ms
```

Full error log
`[2021-02-19 01:33:50,367] ERROR ErrorData(originalTopic=reporting-rds.v_campaign_principle_metrics, timestamp=1613698298911, partition=1, offset=1072205, exception=java.util.concurrent.TimeoutException: Tasks 1 cancelled after timeout of 30000 ms., key=Struct{hash=98e381f7c1ec1cc95e749a0e983e8524}, value=Struct{campaign_id=13739182,campaign_name=IHM_Be The Match_ATLANTA Lineworkers Recruitment OTT 2021_Xandr_OTT_OTTP_01.11.21_09.30.2021 c28eaa13-2ac6-45cc-a09d-18066c3e05c3,publisher=xandr,ad_account_i, executingClass=class kotlinx.coroutines.BlockingCoroutine) (streams.kafka.connect.sink.Neo4jSinkTask:32) java.util.concurrent.TimeoutException: Tasks 1 cancelled after timeout of 30000 ms. 	at streams.kafka.connect.sink.Neo4jService$awaitAll$$inlined$whileSelect$lambda$2.invokeSuspend(Neo4jService.kt:155) 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56) 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:561) 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:727) 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:667) 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:655) 	Suppressed: org.neo4j.driver.exceptions.ServiceUnavailableException: Connection to the database terminated. Please ensure that your database is listening on the correct host and port and that you have compatible encryption settings both on Neo4j server and driver. Note that the default encryption setting has changed in Neo4j 4.0. 		at org.neo4j.driver.internal.util.Futures.blockingGet(Futures.java:143) 		at org.neo4j.driver.internal.InternalResult.blockingGet(InternalResult.java:128) 		at org.neo4j.driver.internal.InternalResult.consume(InternalResult.java:117) 		at streams.kafka.connect.sink.Neo4jService$write$1$1$1.execute(Neo4jService.kt:119) 		at streams.kafka.connect.sink.Neo4jService$write$1$1$1.execute(Neo4jService.kt:36) 		at org.neo4j.driver.internal.InternalSession.lambda$transaction$4(InternalSession.java:150) 		at org.neo4j.driver.internal.retry.ExponentialBackoffRetryLogic.retry(ExponentialBackoffRetryLogic.java:102) 		at org.neo4j.driver.internal.InternalSession.transaction(InternalSession.java:146) 		at org.neo4j.driver.internal.InternalSession.writeTransaction(InternalSession.java:124) 		at org.neo4j.driver.internal.InternalSession.writeTransaction(InternalSession.java:118) 		at streams.kafka.connect.sink.Neo4jService$write$1$1.invoke(Neo4jService.kt:118) 		at streams.kafka.connect.sink.Neo4jService$write$1$1.invoke(Neo4jService.kt:36) 		at streams.utils.CoroutineUtilsKt.retryForException(CoroutineUtils.kt:7) 		at streams.kafka.connect.sink.Neo4jService$write$1.invokeSuspend(Neo4jService.kt:116) 		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) 		at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56) 		at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:271) 		at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:79) 		at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:54) 		at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source) 		at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:36) 		at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source) 		at streams.kafka.connect.sink.Neo4jService.write(Neo4jService.kt:115) 		at streams.service.StreamsSinkService.writeWithCypherTemplate(StreamsSinkService.kt:37) 		at streams.service.StreamsSinkService.writeForTopic(StreamsSinkService.kt:43) 		at streams.kafka.connect.sink.Neo4jService$writeDataAsync$2$invokeSuspend$$inlined$flatMap$lambda$1.invokeSuspend(Neo4jService.kt:182) 		... 6 more 		Suppressed: org.neo4j.driver.internal.util.ErrorUtil$InternalExceptionCause 			at org.neo4j.driver.internal.util.ErrorUtil.newConnectionTerminatedError(ErrorUtil.java:53) 			at org.neo4j.driver.internal.util.ErrorUtil.newConnectionTerminatedError(ErrorUtil.java:46) 			at org.neo4j.driver.internal.async.inbound.ChannelErrorHandler.channelInactive(ChannelErrorHandler.java:76) 			at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) 			at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) 			at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241) 			at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:389) 			at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:354) 			at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) 			at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) 			at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241) 			at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:389) 			at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:354) 			at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) 			at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) 			at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241) 			at org.neo4j.driver.internal.shaded.io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405) 			at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) 			at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) 			at org.neo4j.driver.internal.shaded.io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901) 			at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:818) 			at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) 			at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) 			at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497) 			at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) 			at org.neo4j.driver.internal.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) 			at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) 			at java.lang.Thread.run(Thread.java:748) 		Suppressed: org.neo4j.driver.exceptions.ServiceUnavailableException: Connection to the database terminated. Please ensure that your database is listening on the correct host and port and that you have compatible encryption settings both on Neo4j server and driver. Note that the default encryption setting has changed in Neo4j 4.0. 			... 32 more 			Suppressed: org.neo4j.driver.internal.util.ErrorUtil$InternalExceptionCause 				at org.neo4j.driver.internal.util.ErrorUtil.newConnectionTerminatedError(ErrorUtil.java:53) 				at org.neo4j.driver.internal.util.ErrorUtil.newConnectionTerminatedError(ErrorUtil.java:46) 				at org.neo4j.driver.internal.async.inbound.ChannelErrorHandler.channelInactive(ChannelErrorHandler.java:76) 				at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) 				at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) 				at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241) 				at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:389) 				at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:354) 				at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) 				at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) 				at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241) 				at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:389) 				at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:354) 				at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) 				at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) 				at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241) 				at org.neo4j.driver.internal.shaded.io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405) 				at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) 				at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) 				at org.neo4j.driver.internal.shaded.io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901) 				at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:818) 				at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) 				at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) 				at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497) 				at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) 				at org.neo4j.driver.internal.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) 				at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) 				at java.lang.Thread.run(Thread.java:748), ErrorData(originalTopic=reporting-rds.v_campaign_principle_metrics, timestamp=1613698298911, partition=1, offset=1072205, exception=java.util.concurrent.TimeoutException: Tasks 1 cancelled after timeout of 30000 ms., key=Struct{hash=98e381f7c1ec1cc95e749a0e983e8524}, value=Struct{campaign_id=13739182,campaign_name=IHM_Be The Match_ATLANTA Lineworkers Recruitment OTT 2021_Xandr_OTT_OTTP_01.11.21_09.30.2021 c28eaa13-2ac6-45cc-a09d-18066c3e05c3,publisher=xandr,ad_account_i, executingClass=class kotlinx.coroutines.BlockingCoroutine)`

It seems the error causes missing data issue on neo4j.

**Comment by Tin-Nguyen** [comment]
I have just checked neo4j.conf file. There are some settings I don't think it's related to the issue (not 100% sure), but probably the driver is doing LDAP connection

```
# The timeout for establishing an LDAP connection.
dbms.security.ldap.connection_timeout=30000

# The timeout for an LDAP read request (i.e. search). A value of 0 means wait
# for a response indefinitely.
dbms.security.ldap.read_timeout=30000
```
We don't use LDAP, disabling the setting can help to resolve the issue?

**Comment by Tin-Nguyen** [comment]
it seems after applying some settings below under neo4j sink connector, the issue has been resolved

```
neo4j.batch.size = 100
neo4j.batch.timeout.msecs = 60000
neo4j.connection.acquisition.timeout.msecs = 60000
neo4j.connection.liveness.check.timeout.msecs = 60000
neo4j.connection.max.lifetime.msecs = 3600000
neo4j.connection.max.pool.size = 100
neo4j.retry.backoff.msecs = 30000
neo4j.retry.max.attemps = 5
```
