### ISSUE TITLE
Struct can not be created from an array with optional elements

### ISSUE THREAD

**Issue by TomVanWemmel** [neo4j-contrib/neo4j-streams#553]
I'm trying to create a Neo4jSourceConnector which also uses SMT to extract a key from the query result. 
The config parameter `neo4j.enforce.schema` is used to create the struct.

## Expected Behavior
A struct should be created from the result and the data should be added to the given topic. 

## Actual Behavior 
A DataException occurs with the following stacktrace. 

```
org.apache.kafka.connect.errors.DataException: Invalid Java object for schema with type STRING: class java.util.LinkedHashMap
	at org.apache.kafka.connect.data.ConnectSchema.validateValue(ConnectSchema.java:246)
	at org.apache.kafka.connect.data.ConnectSchema.validateValue(ConnectSchema.java:213)
	at org.apache.kafka.connect.data.ConnectSchema.validateValue(ConnectSchema.java:259)
	at org.apache.kafka.connect.data.ConnectSchema.validateValue(ConnectSchema.java:213)
	at org.apache.kafka.connect.data.ConnectSchema.validateValue(ConnectSchema.java:265)
	at org.apache.kafka.connect.data.ConnectSchema.validateValue(ConnectSchema.java:213)
	at org.apache.kafka.connect.data.ConnectSchema.validateValue(ConnectSchema.java:259)
	at org.apache.kafka.connect.data.Struct.put(Struct.java:216)
	at streams.kafka.connect.utils.ConnectExtensionFunctionsKt.neo4jToKafka(ConnectExtensionFunctions.kt:62)
	at streams.kafka.connect.utils.ConnectExtensionFunctionsKt.asStruct(ConnectExtensionFunctions.kt:42)
	at streams.kafka.connect.source.SourceRecordBuilder.build(SourceRecordBuilder.kt:59)
	at streams.kafka.connect.source.Neo4jSourceService.toSourceRecord(Neo4jSourceService.kt:107)
	at streams.kafka.connect.source.Neo4jSourceService.access$toSourceRecord(Neo4jSourceService.kt:28)
	at streams.kafka.connect.source.Neo4jSourceService$job$1.invokeSuspend$lambda-1(Neo4jSourceService.kt:84)
	at org.neo4j.driver.internal.InternalSession.lambda$transaction$4(InternalSession.java:137)
	at org.neo4j.driver.internal.retry.ExponentialBackoffRetryLogic.retry(ExponentialBackoffRetryLogic.java:106)
	at org.neo4j.driver.internal.InternalSession.transaction(InternalSession.java:134)
	at org.neo4j.driver.internal.InternalSession.readTransaction(InternalSession.java:103)
	at streams.kafka.connect.source.Neo4jSourceService$job$1.invokeSuspend(Neo4jSourceService.kt:79)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
....
```

**Note:** When the order of children is reversed, the exception does not occur. 

## How to Reproduce the Problem

Use the following connector 
```
{
  "name": "neo4j-source",
  "config": {
    "topic": "neo4j-output-topic",
    "connector.class": "streams.kafka.connect.source.Neo4jSourceConnector",
    "key.converter": "org.apache.kafka.connect.storage.StringConverter",
    "key.converter.schemas.enable": "false",
    "value.converter": "org.apache.kafka.connect.json.JsonConverter",
    "value.converter.schemas.enable": "false",
    "neo4j.server.uri": "NEO4J_SERVER",
    "neo4j.authentication.basic.username": "NEO4J_USERNAME",
    "neo4j.authentication.basic.password": "NEO4J_PASSWORD",
    "neo4j.streaming.poll.interval.msecs": 5000,
    "neo4j.streaming.from": "ALL",
    "neo4j.source.query": "WITH {id: 'ROOT_ID',root: [{ children: [] },{ children: [{ name: \"child\" }] }]} AS data RETURN data, data.id AS id",
    "neo4j.enforce.schema" : true,
    "transforms": "extractKey,extractValue",
    "transforms.extractKey.type": "org.apache.kafka.connect.transforms.ExtractField$Key",
    "transforms.extractKey.field": "id",
    "transforms.extractValue.type": "org.apache.kafka.connect.transforms.ExtractField$Value",
    "transforms.extractValue.field": "data"
  }
}
```

### Simple Dataset
The query from the connector in a more readable way. 
```
WITH 
{
  id: 'ROOT_ID',
  root: [
    { children: [] },
    { children: [{ name: "child" }] }
  ]
} AS data RETURN data, data.id AS id
```

## Specifications

Currently used versions

### Versions

  - OS: N/A
  - Neo4j: 5.3.0
  - Neo4j-Streams: 5.0.2

**Comment by conker84** [comment]
@TomVanWemmel thank you so much for reaching us.
We fixed the bug, if you want we can share an artifact in order to test it in your env.
Cheers
Andrea

**Comment by TomVanWemmel** [comment]
Thanks @conker84 !
I've used your branch to test a bigger example and it works perfectly
