### ISSUE TITLE
( Impact on BC/DR - Data loss ) - High priority, Nodes with PointValue property cannot be successfully sink to Neo4j

### ISSUE THREAD

**Issue by yhhongyang** [neo4j-contrib/neo4j-streams#559]
## Guidelines

Please note that GitHub issues are only meant for bug reports/feature requests. If you have questions on how to use Streams, please ask on [StackOverflow](https://stackoverflow.com/questions/tagged/neo4j-streams) instead of creating an issue here.

## Expected Behavior (Mandatory)

I have two Neo4j instances and I use the neo4j-streams plugin to stream data from one instance to another. 

## Actual Behavior (Mandatory)

In the source instance, I create a node that with a point property, like `CREATE (n:Test{name: 'Name1',point: point({longitude: 56.7, latitude: 12.78, height: 8})})`, and in sink instance, it throw an exception and the node is not stored in sink instance
```
ErrorData(originalTopic=my-topic, timestamp=1684462474785, partition=0, offset=29675, exception=org.neo4j.graphdb.QueryExecutionException: Property values can only be of primitive types or arrays thereof. Encountered: Map{latitude -> Double(5.670000e+01), longitude -> Double(1.278000e+01), height -> Double(8.000000e+00)}., key=null, value={"meta":{"timestamp":1684379795919,"username":"test","txId":10101,"txEventId":0,"txEventsCount":1,"operation":"created","source":{"hostname":"xxxxx"}},"payload":{"id":"2","befo, executingClass=class streams.kafka.KafkaAutoCommitEventConsumer)
	at streams.service.errors.KafkaErrorService.report(KafkaErrorService.kt:37) ~[neo4j-streams-4.1.2.jar:?]
	at streams.kafka.KafkaAutoCommitEventConsumer.executeAction(KafkaAutoCommitEventConsumer.kt:97) ~[neo4j-streams-4.1.2.jar:?]
	at streams.kafka.KafkaAutoCommitEventConsumer.readSimple(KafkaAutoCommitEventConsumer.kt:89) ~[neo4j-streams-4.1.2.jar:?]
	at streams.kafka.KafkaAutoCommitEventConsumer.read(KafkaAutoCommitEventConsumer.kt:118) ~[neo4j-streams-4.1.2.jar:?]
	at streams.kafka.KafkaEventSink$createJob$1.invokeSuspend(KafkaEventSink.kt:163) [neo4j-streams-4.1.2.jar:?]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) [neo4j-streams-4.1.2.jar:?]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) [neo4j-streams-4.1.2.jar:?]
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39) [neo4j-streams-4.1.2.jar:?]
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95) [neo4j-streams-4.1.2.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571) [neo4j-streams-4.1.2.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) [neo4j-streams-4.1.2.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678) [neo4j-streams-4.1.2.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665) [neo4j-streams-4.1.2.jar:?]
```

Here is my sink configuration
```
streams.sink.topic.cdc.sourceId=my-topic
streams.sink.topic.cdc.sourceId.labelName = Test
streams.sink.topic.cdc.sourceId.idName = neo4jSyncId
streams.sink.enabled=true
streams.source.enabled=false
kafka.bootstrap.servers=localhost:9092 
kafka.group.id=ss-8
```

### Simple Dataset (where it's possibile)

```
//Insert here a set of Cypher statements that helps us to reproduce the problem

```

### Steps (Mandatory)

  1. 
  1.
  1.

## Specifications (Mandatory)

Currently used versions

### Versions

  - OS:
  - Neo4j:
  - Neo4j-Streams:

**Comment by yhhongyang** [comment]
This issue also exists in the latest Neo4j Kafka Connector v5.0.2. It seems that the source part serializes the PointValue to a Map, but the sink doesn't deserialize the Map back to a PointValue.

**Comment by conker84** [comment]
Sorry there is a misunderstanding, you cannot use the connectors in that way. The source data must come from Neo4j Streams Plugin (the one installed into Neo4j) and not from the Neo4j Kafka Connector

**Comment by yhhongyang** [comment]
> Sorry there is a misunderstanding, you cannot use the connectors in that way. The source data must come from Neo4j Streams Plugin (the one installed into Neo4j) and not from the Neo4j Kafka Connector

@conker84 I did first use  `Neo4j Steams Plugin` to source data from instance A,  and sink to instance B, please see the content of this issue. As I found this sink issue in  `Neo4j Steams Plugin`,  I want to see if the latest connector solves this problem, then I tried the  Neo4j Kafka Connector.

In my scenario, I still want to use `Neo4j Steams Plugin` as I found the connector can not capture delete opeartors
