### ISSUE TITLE
Build compilation failure due to failing IT cases

### ISSUE THREAD

**Issue by yasirhusain** [neo4j-contrib/neo4j-streams#81]
## Expected Behavior (Mandatory)
All Unit and IT cases should pass before build compilation is successful.

## Actual Behavior (Mandatory)
When compiling release on the latest version of Neo4j, the Integration test named 'streams.integrations.SampleKafkaIT' is failing due to which build compilation fails. Build compiles successfully after we skip the tests. Exception trace is attached
[stack_trace.txt](https://github.com/neo4j-contrib/neo4j-streams/files/2588414/stack_trace.txt)
.

### Steps (Mandatory)

  1. Take the updated code from https://github.com/neo4j-contrib/neo4j-streams.git
  2. Execute command, "mvn clean install". Build will display error on step "streams.integrations.SampleKafkaIT  Time elapsed: 10.369 s  <<< ERROR!" causing the build to fail
  3. Build the code by executing command, "mvn clean install -Dmaven.test.skip=true"

## Specifications (Mandatory)

Currently used versions: 3.4.7.1

**Comment by conker84** [comment]
Hi @yasirhusain do you have Docker installed? It seems like TestContainers cannot be started:

```
[ERROR] streams.integrations.SampleKafkaIT  Time elapsed: 10.369 s  <<< ERROR!
java.lang.ExceptionInInitializerError
	at streams.integrations.SampleKafkaIT.<clinit>(SampleKafkaIT.kt:35)
```

[SampleKafkaIT.kt:35](https://github.com/neo4j-contrib/neo4j-streams/blob/cf2872417ccb48dc91a0e8a7dd8c19ec51fbbe29/producer/src/test/kotlin/streams/integrations/SampleKafkaIT.kt#L35)

**Comment by yasirhusain** [comment]
Hi @conker84, No docker is not installed on the build machine. Let me install docker and see if it works.

**Comment by conker84** [comment]
@yasirhusain any feedback ok this?

**Comment by yasirhusain** [comment]
Hi @conker84,

I apologize for the late response. I have configured docker on my local instance having version
Docker version 18.06.1-ce, build e68fc7a

Neo4j is up and running as well but encountering the below error while trying to build JAR.

[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running streams.StreamsTransactionEventHandlerRelTest
[INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.201 s - in streams.StreamsTransactionEventHandlerRelTest
[INFO] Running streams.RoutingConfigurationTest
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.07 s - in streams.RoutingConfigurationTest
[INFO] Running streams.serialization.JacksonUtilTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.321 s - in streams.serialization.JacksonUtilTest
[INFO] Running streams.kafka.KafkaConfigurationTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 s - in streams.kafka.KafkaConfigurationTest
[INFO] Running streams.integrations.SampleKafkaIT
        ℹ︎ Checking the system...
        ✔ Docker version should be at least 1.6.0
        ✔ Docker environment should have more than 2GB free disk space
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 68.458 s <<< FAILURE! - in streams.integrations.SampleKafkaIT
[ERROR] testCreateNode(streams.integrations.SampleKafkaIT)  Time elapsed: 16.755 s  <<< FAILURE!
java.lang.AssertionError: expected:<1> but was:<0>
	at streams.integrations.SampleKafkaIT.testCreateNode(SampleKafkaIT.kt:72)

[INFO] Running streams.integrations.StreamsTransactionEventHandlerIT
Exception in thread "Thread-2" org.neo4j.kernel.impl.core.ThreadToStatementContextBridge$BridgeDatabaseShutdownException: This database is shutdown.
	at org.neo4j.kernel.impl.core.ThreadToStatementContextBridge.checkIfShutdown(ThreadToStatementContextBridge.java:98)
	at org.neo4j.kernel.impl.core.ThreadToStatementContextBridge.getKernelTransactionBoundToThisThread(ThreadToStatementContextBridge.java:114)
	at org.neo4j.kernel.impl.query.Neo4jTransactionalContext.kernelTransaction(Neo4jTransactionalContext.java:105)
	at org.neo4j.cypher.internal.runtime.interpreted.TransactionalContextWrapper.dataRead(TransactionalContextWrapper.scala:59)
	at org.neo4j.cypher.internal.runtime.interpreted.TransactionBoundPlanContext$.apply(TransactionBoundPlanContext.scala:41)
	at org.neo4j.cypher.internal.compatibility.v3_4.Compatibility$$anon$1$$anonfun$plan$1.apply(Compatibility.scala:108)
	at org.neo4j.cypher.internal.compatibility.v3_4.Compatibility$$anon$1$$anonfun$plan$1.apply(Compatibility.scala:104)
	at org.neo4j.cypher.exceptionHandler$runSafely$.apply(exceptionHandler.scala:89)
	at org.neo4j.cypher.internal.compatibility.v3_4.Compatibility$$anon$1.plan(Compatibility.scala:104)
	at org.neo4j.cypher.internal.ExecutionEngine$$anon$3.produceWithExistingTX(ExecutionEngine.scala:185)
	at org.neo4j.cypher.internal.ExecutionEngine$$anon$3.produceWithExistingTX(ExecutionEngine.scala:182)
	at org.neo4j.cypher.internal.compatibility.QueryCache$$anonfun$1.apply(CacheAccessor.scala:41)
	at org.neo4j.cypher.internal.compatibility.MonitoringCacheAccessor$$anonfun$2.apply(CacheAccessor.scala:68)
	at org.neo4j.cypher.internal.compatibility.LFUCache$$anon$1.apply(LFUCache.scala:31)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$16(BoundedLocalCache.java:1973)
	at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1853)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:1971)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:1954)
	at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:113)
	at com.github.benmanes.caffeine.cache.LocalManualCache.get(LocalManualCache.java:54)
	at org.neo4j.cypher.internal.compatibility.LFUCache.getOrElseUpdate(LFUCache.scala:30)
	at org.neo4j.cypher.internal.compatibility.LFUCache.apply(LFUCache.scala:48)
	at org.neo4j.cypher.internal.compatibility.MonitoringCacheAccessor.getOrElseUpdate(CacheAccessor.scala:66)
	at org.neo4j.cypher.internal.compatibility.QueryCache.getOrElseUpdate(CacheAccessor.scala:39)
	at org.neo4j.cypher.internal.ExecutionEngine.liftedTree1$1(ExecutionEngine.scala:190)
	at org.neo4j.cypher.internal.ExecutionEngine.planQuery(ExecutionEngine.scala:172)
	at org.neo4j.cypher.internal.ExecutionEngine.execute(ExecutionEngine.scala:115)
	at org.neo4j.cypher.internal.javacompat.ExecutionEngine.executeQuery(ExecutionEngine.java:61)
	at org.neo4j.kernel.impl.factory.ClassicCoreSPI.executeQuery(ClassicCoreSPI.java:79)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacade.execute(GraphDatabaseFacade.java:428)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacade.execute(GraphDatabaseFacade.java:411)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacade.execute(GraphDatabaseFacade.java:395)
	at streams.integrations.SampleKafkaIT.createNode(SampleKafkaIT.kt:53)
	at streams.integrations.SampleKafkaIT.access$createNode(SampleKafkaIT.kt:18)
	at streams.integrations.SampleKafkaIT$testCreateNode$1.run(SampleKafkaIT.kt:69)
	at java.lang.Thread.run(Thread.java:745)
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.917 s - in streams.integrations.StreamsTransactionEventHandlerIT
[INFO] Running streams.StreamsTransactionEventHandlerTest
[INFO] Tests run: 14, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.024 s - in streams.StreamsTransactionEventHandlerTest
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   SampleKafkaIT.testCreateNode:72 expected:<1> but was:<0>
[INFO] 
[ERROR] Tests run: 31, Failures: 1, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Neo4j Streams - Parent ............................. SUCCESS [  3.014 s]
[INFO] Neo4j Streams - Producer ........................... FAILURE [01:36 min]
[INFO] Neo4j Streams - Consumer ........................... SKIPPED
[INFO] Neo4j Streams - Docs ............................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:39 min
[INFO] Finished at: 2018-11-22T12:09:36+05:00
[INFO] Final Memory: 57M/701M
[INFO] ------------------------------------------------------------------------

**Comment by yasirhusain** [comment]
Hi @conker84,

I have taken latest update today (commit 9fdd80daf94235f92c6f1d0eaa8d1906cbfbc663) and see that the unit tests are passing. Thank you for your help.
